### ISSUE TITLE
recommanded way to load external packages in a template

### ISSUE THREAD

**Issue by belgac** [dchrzanowski/mtml#4]
Is there an official way to load an external package inside a template file to use it in templating?

For example i created a namer function in another project and i want to use it in my template, how can i load it?

**Comment by dchrzanowski** [comment]
In the next version of mtml I'll add a feature in which you can import a js functions file via the scenario file.

However, for the time being you can do [this](https://stackoverflow.com/a/30539675/5458001)

**Comment by belgac** [comment]
Thanks a lot :)

**Comment by dchrzanowski** [comment]
No problem!
